import arms1Type1 from './flowbots/arms/1.svg'
import arms2Type1 from './flowbots/arms/2.svg'
import arms3Type1 from './flowbots/arms/3.svg'
import arms4Type1 from './flowbots/arms/4.svg'
import arms5Type1 from './flowbots/arms/5.svg'
import arms6Type1 from './flowbots/arms/6.svg'
import arms7Type1 from './flowbots/arms/7.svg'
import arms8Type1 from './flowbots/arms/8.svg'
import arms9Type1 from './flowbots/arms/9.svg'
import arms10Type1 from './flowbots/arms/10.svg'
import arms11Type1 from './flowbots/arms/11.svg'
import arms12Type1 from './flowbots/arms/12.svg'
import arms13Type1 from './flowbots/arms/13.svg'
import arms14Type1 from './flowbots/arms/14.svg'
import arms15Type1 from './flowbots/arms/15.svg'
import arms16Type1 from './flowbots/arms/16.svg'
import arms17Type1 from './flowbots/arms/17.svg'
import arms18Type1 from './flowbots/arms/18.svg'
import arms19Type1 from './flowbots/arms/19.svg'
import arms1Type2 from './flowbots/arms/1p.svg'
import arms2Type2 from './flowbots/arms/2p.svg'
import arms3Type2 from './flowbots/arms/3p.svg'
import arms4Type2 from './flowbots/arms/4p.svg'
import arms5Type2 from './flowbots/arms/5p.svg'
import arms6Type2 from './flowbots/arms/6p.svg'
import arms7Type2 from './flowbots/arms/7p.svg'
import arms8Type2 from './flowbots/arms/8p.svg'
import arms9Type2 from './flowbots/arms/9p.svg'
import arms10Type2 from './flowbots/arms/10p.svg'
import arms11Type2 from './flowbots/arms/11p.svg'
import arms12Type2 from './flowbots/arms/12p.svg'
import arms13Type2 from './flowbots/arms/13p.svg'
import arms14Type2 from './flowbots/arms/14p.svg'
import arms15Type2 from './flowbots/arms/15p.svg'
import arms16Type2 from './flowbots/arms/16p.svg'
import arms17Type2 from './flowbots/arms/17p.svg'
import arms18Type2 from './flowbots/arms/18p.svg'
import arms19Type2 from './flowbots/arms/19p.svg'

import body1Type1 from './flowbots/body/1.svg'
import body2Type1 from './flowbots/body/2.svg'
import body3Type1 from './flowbots/body/3.svg'
import body4Type1 from './flowbots/body/4.svg'
import body5Type1 from './flowbots/body/5.svg'
import body6Type1 from './flowbots/body/6.svg'
import body7Type1 from './flowbots/body/7.svg'
import body8Type1 from './flowbots/body/8.svg'
import body9Type1 from './flowbots/body/9.svg'
import body10Type1 from './flowbots/body/10.svg'
import body11Type1 from './flowbots/body/11.svg'
import body12Type1 from './flowbots/body/12.svg'
import body13Type1 from './flowbots/body/13.svg'
import body1Type2 from './flowbots/body/1p.svg'
import body2Type2 from './flowbots/body/2p.svg'
import body3Type2 from './flowbots/body/3p.svg'
import body4Type2 from './flowbots/body/4p.svg'
import body5Type2 from './flowbots/body/5p.svg'
import body6Type2 from './flowbots/body/6p.svg'
import body7Type2 from './flowbots/body/7p.svg'
import body8Type2 from './flowbots/body/8p.svg'
import body9Type2 from './flowbots/body/9p.svg'
import body10Type2 from './flowbots/body/10p.svg'
import body11Type2 from './flowbots/body/11p.svg'
import body12Type2 from './flowbots/body/12p.svg'
import body13Type2 from './flowbots/body/13p.svg'

import grill1Type1 from './flowbots/grill/1.svg'
import grill2Type1 from './flowbots/grill/2.svg'
import grill3Type1 from './flowbots/grill/3.svg'
import grill4Type1 from './flowbots/grill/4.svg'
import grill5Type1 from './flowbots/grill/5.svg'
import grill6Type1 from './flowbots/grill/6.svg'
import grill7Type1 from './flowbots/grill/7.svg'
import grill8Type1 from './flowbots/grill/8.svg'
import grill9Type1 from './flowbots/grill/9.svg'
import grill10Type1 from './flowbots/grill/10.svg'
import grill11Type1 from './flowbots/grill/11.svg'
import grill12Type1 from './flowbots/grill/12.svg'
import grill13Type1 from './flowbots/grill/13.svg'
import grill14Type1 from './flowbots/grill/14.svg'
import grill15Type1 from './flowbots/grill/15.svg'
import grill16Type1 from './flowbots/grill/16.svg'
import grill17Type1 from './flowbots/grill/17.svg'
import grill18Type1 from './flowbots/grill/18.svg'
import grill19Type1 from './flowbots/grill/19.svg'
import grill20Type1 from './flowbots/grill/20.svg'
import grill21Type1 from './flowbots/grill/21.svg'
import grill1Type2 from './flowbots/grill/1p.svg'
import grill2Type2 from './flowbots/grill/2p.svg'
import grill3Type2 from './flowbots/grill/3p.svg'
import grill4Type2 from './flowbots/grill/4p.svg'
import grill5Type2 from './flowbots/grill/5p.svg'
import grill6Type2 from './flowbots/grill/6p.svg'
import grill7Type2 from './flowbots/grill/7p.svg'
import grill8Type2 from './flowbots/grill/8p.svg'
import grill9Type2 from './flowbots/grill/9p.svg'
import grill10Type2 from './flowbots/grill/10p.svg'
import grill11Type2 from './flowbots/grill/11p.svg'
import grill12Type2 from './flowbots/grill/12p.svg'
import grill13Type2 from './flowbots/grill/13p.svg'
import grill14Type2 from './flowbots/grill/14p.svg'
import grill15Type2 from './flowbots/grill/15p.svg'
import grill16Type2 from './flowbots/grill/16p.svg'
import grill17Type2 from './flowbots/grill/17p.svg'
import grill18Type2 from './flowbots/grill/18p.svg'
import grill19Type2 from './flowbots/grill/19p.svg'
import grill20Type2 from './flowbots/grill/20p.svg'
import grill21Type2 from './flowbots/grill/21p.svg'

import head1Type1 from './flowbots/head/1.svg'
import head2Type1 from './flowbots/head/2.svg'
import head3Type1 from './flowbots/head/3.svg'
import head4Type1 from './flowbots/head/4.svg'
import head5Type1 from './flowbots/head/5.svg'
import head6Type1 from './flowbots/head/6.svg'
import head7Type1 from './flowbots/head/7.svg'
import head8Type1 from './flowbots/head/8.svg'
import head9Type1 from './flowbots/head/9.svg'
import head10Type1 from './flowbots/head/10.svg'
import head11Type1 from './flowbots/head/11.svg'
import head12Type1 from './flowbots/head/12.svg'
import head13Type1 from './flowbots/head/13.svg'
import head1Type2 from './flowbots/head/1p.svg'
import head2Type2 from './flowbots/head/2p.svg'
import head3Type2 from './flowbots/head/3p.svg'
import head4Type2 from './flowbots/head/4p.svg'
import head5Type2 from './flowbots/head/5p.svg'
import head6Type2 from './flowbots/head/6p.svg'
import head7Type2 from './flowbots/head/7p.svg'
import head8Type2 from './flowbots/head/8p.svg'
import head9Type2 from './flowbots/head/9p.svg'
import head10Type2 from './flowbots/head/10p.svg'
import head11Type2 from './flowbots/head/11p.svg'
import head12Type2 from './flowbots/head/12p.svg'
import head13Type2 from './flowbots/head/13p.svg'

import legs1Type1 from './flowbots/legs/1.svg'
import legs2Type1 from './flowbots/legs/2.svg'
import legs3Type1 from './flowbots/legs/3.svg'
import legs4Type1 from './flowbots/legs/4.svg'
import legs5Type1 from './flowbots/legs/5.svg'
import legs6Type1 from './flowbots/legs/6.svg'
import legs7Type1 from './flowbots/legs/7.svg'
import legs8Type1 from './flowbots/legs/8.svg'
import legs9Type1 from './flowbots/legs/9.svg'
import legs10Type1 from './flowbots/legs/10.svg'
import legs11Type1 from './flowbots/legs/11.svg'
import legs12Type1 from './flowbots/legs/12.svg'
import legs13Type1 from './flowbots/legs/13.svg'
import legs14Type1 from './flowbots/legs/14.svg'
import legs1Type2 from './flowbots/legs/1p.svg'
import legs2Type2 from './flowbots/legs/2p.svg'
import legs3Type2 from './flowbots/legs/3p.svg'
import legs4Type2 from './flowbots/legs/4p.svg'
import legs5Type2 from './flowbots/legs/5p.svg'
import legs6Type2 from './flowbots/legs/6p.svg'
import legs7Type2 from './flowbots/legs/7p.svg'
import legs8Type2 from './flowbots/legs/8p.svg'
import legs9Type2 from './flowbots/legs/9p.svg'
import legs10Type2 from './flowbots/legs/10p.svg'
import legs11Type2 from './flowbots/legs/11p.svg'
import legs12Type2 from './flowbots/legs/12p.svg'
import legs13Type2 from './flowbots/legs/13p.svg'
import legs14Type2 from './flowbots/legs/14p.svg'

import panel1Type1 from './flowbots/panel/1.svg'
import panel2Type1 from './flowbots/panel/2.svg'
import panel3Type1 from './flowbots/panel/3.svg'
import panel4Type1 from './flowbots/panel/4.svg'
import panel5Type1 from './flowbots/panel/5.svg'
import panel6Type1 from './flowbots/panel/6.svg'
import panel7Type1 from './flowbots/panel/7.svg'
import panel8Type1 from './flowbots/panel/8.svg'
import panel9Type1 from './flowbots/panel/9.svg'
import panel10Type1 from './flowbots/panel/10.svg'
import panel11Type1 from './flowbots/panel/11.svg'
import panel12Type1 from './flowbots/panel/12.svg'
import panel13Type1 from './flowbots/panel/13.svg'
import panel14Type1 from './flowbots/panel/14.svg'
import panel1Type2 from './flowbots/panel/1p.svg'
import panel2Type2 from './flowbots/panel/2p.svg'
import panel3Type2 from './flowbots/panel/3p.svg'
import panel4Type2 from './flowbots/panel/4p.svg'
import panel5Type2 from './flowbots/panel/5p.svg'
import panel6Type2 from './flowbots/panel/6p.svg'
import panel7Type2 from './flowbots/panel/7p.svg'
import panel8Type2 from './flowbots/panel/8p.svg'
import panel9Type2 from './flowbots/panel/9p.svg'
import panel10Type2 from './flowbots/panel/10p.svg'
import panel11Type2 from './flowbots/panel/11p.svg'
import panel12Type2 from './flowbots/panel/12p.svg'
import panel13Type2 from './flowbots/panel/13p.svg'
import panel14Type2 from './flowbots/panel/14p.svg'

export const parts = {
  arms: {
    type1: [arms1Type1, arms2Type1, arms3Type1, arms4Type1, arms5Type1, arms6Type1, arms7Type1, arms8Type1, arms9Type1,
      arms10Type1, arms11Type1, arms12Type1, arms13Type1, arms14Type1, arms15Type1, arms16Type1, arms17Type1, arms18Type1, arms19Type1],
    type2: [arms1Type2, arms2Type2, arms3Type2, arms4Type2, arms5Type2, arms6Type2, arms7Type2, arms8Type2, arms9Type2,
      arms10Type2, arms11Type2, arms12Type2, arms13Type2, arms14Type2, arms15Type2, arms16Type2, arms17Type2, arms18Type2, arms19Type2]
  },
  body: {
    type1: [body1Type1, body2Type1, body3Type1, body4Type1, body5Type1, body6Type1, body7Type1, body8Type1, body9Type1,
      body10Type1, body11Type1, body12Type1, body13Type1],
    type2: [body1Type2, body2Type2, body3Type2, body4Type2, body5Type2, body6Type2, body7Type2, body8Type2, body9Type2,
      body10Type2, body11Type2, body12Type2, body13Type2]
  },
  grill: {
    type1: [grill1Type1, grill2Type1, grill3Type1, grill4Type1, grill5Type1, grill6Type1, grill7Type1, grill8Type1, grill9Type1,
      grill10Type1, grill11Type1, grill12Type1, grill13Type1, grill14Type1, grill15Type1, grill16Type1, grill17Type1, grill18Type1, grill19Type1, grill20Type1, grill21Type1],
    type2: [grill1Type2, grill2Type2, grill3Type2, grill4Type2, grill5Type2, grill6Type2, grill7Type2, grill8Type2, grill9Type2,
      grill10Type2, grill11Type2, grill12Type2, grill13Type2, grill14Type2, grill15Type2, grill16Type2, grill17Type2, grill18Type2, grill19Type2, grill20Type2, grill21Type2]
  },
  head: {
    type1: [head1Type1, head2Type1, head3Type1, head4Type1, head5Type1, head6Type1, head7Type1, head8Type1, head9Type1,
      head10Type1, head11Type1, head12Type1, head13Type1],
    type2: [head1Type2, head2Type2, head3Type2, head4Type2, head5Type2, head6Type2, head7Type2, head8Type2, head9Type2,
      head10Type2, head11Type2, head12Type2, head13Type2]
  },
  legs: {
    type1: [legs1Type1, legs2Type1, legs3Type1, legs4Type1, legs5Type1, legs6Type1, legs7Type1, legs8Type1, legs9Type1,
      legs10Type1, legs11Type1, legs12Type1, legs13Type1, legs14Type1],
    type2: [legs1Type2, legs2Type2, legs3Type2, legs4Type2, legs5Type2, legs6Type2, legs7Type2, legs8Type2, legs9Type2,
      legs10Type2, legs11Type2, legs12Type2, legs13Type2, legs14Type2]
  },
  panel: {
    type1: [panel1Type1, panel2Type1, panel3Type1, panel4Type1, panel5Type1, panel6Type1, panel7Type1, panel8Type1, panel9Type1,
      panel10Type1, panel11Type1, panel12Type1, panel13Type1, panel14Type1],
    type2: [panel1Type2, panel2Type2, panel3Type2, panel4Type2, panel5Type2, panel6Type2, panel7Type2, panel8Type2, panel9Type2,
      panel10Type2, panel11Type2, panel12Type2, panel13Type2, panel14Type2]
  }
}
