services:
  has_mongo:
    image: mongo:latest
    container_name: has-mongo
    networks:
      - has-network  # Attach the container to the ch-network
    volumes:
      - ${MONGO_LOCAL_DIR}:/data/db
    restart: always

  has_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    container_name: has-api
    restart: ${RESTART}
    environment:
      - MONGO_URL=mongodb://has_mongo:27017/halfasecond  # Specify the MongoDB connection URL
    depends_on:
      - has_mongo
    networks:
      - has-network  # Attach the container to the ch-network
    env_file: .env
    volumes: # turn on for local dev..
    - ${SRC_CODE_LOCAL_DIR}:/app
    - /app/node_modules

networks:
  host:
    external: true
  has-network:
    driver: bridge
